### ISSUE TITLE
Header/footer whitespace 

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#100]
There is whitespace to right of header and footer on iPad and iPhone 6 - can that be fixed?

**Comment by alecpm** [comment]
Should be fixed.

**Comment by skleinfeldt** [comment]
Haven't tested on iPad yet, but on my iPhone I still see that whitespace. Is there a way to bust the cache on phones?

**Comment by alecpm** [comment]
Looks like it's not a cache issue.  Looks like I fixed it on some pages (project pages), but not on others.  Fix should be up shortly.

**Comment by skleinfeldt** [comment]
Fantastic!!
