### ISSUE TITLE
Mosaic Slider for rich text tile-like things

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#153]
For the news/blog row on the homepage we need a slider for a series of 5 or more rich text tile-like things. The tile-like things will consist of an image (from an existing image or lead image, with a specific crop selected), followed by a header line, maybe followed by a short paragraph. The image and the header line will both link to the same place. The slider behavior should be controlled by an arrow that is the same design as the related slider arrow. The slider behavior should be circular - that is clicking the left or right arrow you will keep cycling through the tile-like things repeatedly.

I'm calling them tile-like things because I assume they can't be mosaic tiles. They could be pages maybe, so it could work similar to the DOaks slider?

**Comment by alecpm** [comment]
I think this can be done with the tesserae slider that's already installed (and is what we use on DOaks). Just create a folder and add `sliderimage` content to it. Then set the Display on the folder to Slider View and maybe adjust the Slider Settings from the action menu. You should then have a nice slider that you can put into mosaic using the "Existing Content Tile".

**Comment by skleinfeldt** [comment]
@alecpm Something is not quite right, the `sliderimage` content type is not on my Add menu, and I don't see Slider View as a Display option.

**Comment by alecpm** [comment]
This should be fixed now.

**Comment by skleinfeldt** [comment]
@alecpm I still don't see `sliderimage` on the Add menu, or Slider View as a Display option... Help?

**Comment by skleinfeldt** [comment]
Thanks @alecpm the tesserae slider stuff is now working. It will be fine for when/if I want to use a full width image slider, but for the news/blog row I actually had a multi-item carousel in mind - essentially the same thing that's needed for #154. I'll leave that ticket open and close this one.
